config/routes.rb
SEZWebsite::Application.routes.draw do

  root :to => 'sez_core#index'

  get  '/about'       => 'sez_core#about'
  get  '/archive'     => 'sez_core#archive'
  get  '/contribute'  => 'sez_core#contribute'
  get  '/contact'     => 'contacts#new',         :as => 'contact'
  post '/contact'     => 'contacts#create',      :as => 'contact_create'
  get  '/game/:id'    => 'sez_core#game',        :as => 'game'
  get  '/feed'        => 'articles#feed',        :as => :feed,    :defaults => { :format => 'rss' }

  resources :articles
  resources :topics
  resources :quizzes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/controllers/sez_core_controller.rb
class SezCoreController < ApplicationController

  before_action :check_for_mobile

  def index
    @title = "Home"
    @articles = Article.order("pubdate DESC").limit(6)
  end

  def about
    @title = "About"
  end

  def contribute
    @title = "Contribute"
  end

  def game
    @title = "Quiz Game"

    @quiz = QuizDecorator.new Quiz.find(params[:id])
  end

end

app/views/sez_core/about.html.haml
#about

  %h2 SEZ について

  %p.header-lead SEZはSimple English Zineの略です。私たちは、ネイティブでない英語学習者向けに、記事やブログをシンプルで分かり易い英語で書いています。難しい語彙については、シンプルな定義と和訳を載せています。

  %p 時おり、よく知らない歴史的または文化的な記述が出てくる記事があるかもしれませんが、カルチャーノートを載せて背景を説明したり、トピックの前後関係を伝えるようにしています。カルチャーノートは日本語で書かれていますので、素早く容易に読むことが出来ます。

  %p それぞれの記事の最後で語彙とカルチャーノートを確認したり、もしくは記事中のリンクにマウスポインターを合わせると画面左下に表示されるポップアップで参考になる情報を見ることが出来ます。音声付きの記事もたくさんあるので、リスニングの練習も出来ます。


  %p SEZは、日本で英語を学ぶ生徒の為の学習ツールとして、少人数の英語教師のグループによって2012年に東京で始まりました。私たちは数多くの異なる文化的背景、職業、国籍からの寄稿者を含むように成長しています。

  %p 私たちはSEZを運営していくにあたって、友人や読者のみなさんから寄与して頂く時間、才能に頼っています。もし私たちを支援したいと思ったら、どうぞ #{link_to "Contribute", contribute_path} ページをみてください。

  %p 私たちは時間の経過とともに、より多くの記事、ブログ、特集を追加していくので、定期的にチェックしてみてください。もし質問、コメント、気になる事、アドバイス、またはお褒めの言葉などがあれば、どうぞ #{link_to "Contact", contact_path} ページにご一報くださいね。ピース！


  .english

    %h2 About

    %p.header-lead SEZ stands for Simple English Zine. We write articles and blogs in simple, easy to understand English for non-native learners of the English language. For difficult Vocabulary we've included simple definitions and a translation in Japanese.

    %p Sometimes there may be unfamiliar historical or cultural references in an article, so we've also included some Culture Notes to explain background and give context to the topic. Culture Notes are written in Japanese so you can read them quickly and easily.

    %p You can find Vocabulary and Culture Notes at the end of each article, or you can hover on links in the article to see helpful information pop up in the bottom left corner of the screen.

    %p Many articles also include audio so you can practice listening as well.

    %p SEZ was started by a small group of English teachers in Tokyo in 2012 as a learning tool for English language students in Japan. We've grown to include contributors from many different cultural backgrounds, professions, and nationalities.

    %p We rely on friends and readers to contribute their time, and talent to keep SEZ going. If you'd like to help us out, please check out the #{link_to "Contribute", contribute_path} page.

    %p We'll be adding more articles, blogs and features to this site as time goes by, so check in with us regularly. Please drop us a line at the #{link_to "Contact", contact_path} page if you have any questions, comments, concerns, advice or praise. Peace!

app/views/sez_core/contribute.html.haml
#contribute

  %h2 Contribute

  %p.header-lead We make this thing because we like making it, and we hope you like reading it. If you'd like to help us continue this project there are many ways you can contribute. We greatly appreciate any kind of support you give. Your support is the only reason we can continue making this magazine.

  %h3 Write Something

  %p We accept manuscripts on a variety of topics, but all writing should be written in simplified English. If you're not sure what that means, feel free to send us something written in your usual style and we may be able to help you simplify it. Generally we like manuscripts that are between 400 and 1,000 words. If you're a non-native speaker and you're writing may have some small mistakes, that's fine! Please don't hesitate to submit. We don't mind if your submission has already been published elsewhere or you plan to publish it again later as long as publishing it in SEZ does not infringe on another copyright. We cannot accept every manuscript that we receive. In the case that you're manuscript is denied we will try to write you back explaining why. Please understand that we do not offer compensation.

  %h3 Make Art

  %p We try to accompany each article with interesting artwork. If you'd like to make artwork (illustration, graphic design, photography, etc.) for an article, please get in touch and send us some samples of your previous work. We can't offer compensation but we're happy to credit you and offer a link back to your site.

  %h3 Help Translate

  %p For every article, it is necessary to do some translation from English to Japanese and vice versa.

  %h3 Help Edit

  %p Each article must be edited for spelling, grammar, and punctuation mistakes, and for factual errors. We would especially appreciate the contributions of people with experience teaching English as a second language to ensure that articles are written at a level appropriate for a non-native speaker.


  %h3 Teach Someone Something For Free

  %p Free education and the free exchange of information are core principles of this magazine. In this spirit, you support us symbolically by sharing some knowledge or skill you have for free with someone in your community.

app/views/sez_core/game.html.haml
%section#quiz-game

  %iframe{:src => "/quizzes/#{@quiz.id}"}

  #quiz-meta
    %section#instructions
      %h3 効果的な使い方
      %p スタートボタンをクリックしてから数秒後に単語の選択肢がいくつか現れます。現れるまでの数秒間に正解となりそうな単語を推測してみてください。選択肢から一つ選んでクリックすると、答えが例文とともに現れます。例文を声に出して読んでみてください。きっと覚えるのに役立つはずです！

    %section#related-quizzes
      %h3 同じ単語を使った他のゲーム
      - unless @quiz.related.empty?
        %ul
          - @quiz.related.each do |quiz|
            = content_tag :li do
              = link_to(quiz.name, game_path(:id => quiz.id))
              %br
              <i>クイズの種類:</i> #{quiz.quiz_type}
      - else
        %p なし

    %section#related-article
      %h3 ゲームが終わったら、記事を読んでみて！
      %div
        = image_tag @quiz.article.image_url(:main)
        = link_to content_tag(:h4, @quiz.article.title), @quiz.article
        %p #{@quiz.article.description}

app/views/sez_core/index.html.haml
.header-lead
  = image_tag "/images/bird-logo.png", :class => "bird-logo"
  %p 優しい英語で書いたウェブマガジン。単語の意味も辞書要らずのポップアップで簡単チェック。ボキャブラリーがどんどん増えます！

%section.catalog
  %ul
    - @articles.each do |article|
      = link_to article do
        %li.catalog-entry
          = image_tag article.image_url(:in_focus)
          .catalog-entry-info
            %h2
              %span.topic-marker #{article.topic.name}
              = article.title
            %p
              %i
                = "#{article.pubdate.strftime('%Y年%m月%d日')} 掲載　#{article.author.name} 著"  unless article.author.name == "SEZ"
            %p #{article.description}
            = render 'layouts/study_tools', :article => article

          = image_tag(add_flag(article.flag_message), :class => "attention-flag") unless article.flag_message.blank?