config/routes.rb
SEZWebsite::Application.routes.draw do

  root :to => 'sez_core#index'

  get  '/about'       => 'sez_core#about'
  get  '/archive'     => 'sez_core#archive'
  get  '/contribute'  => 'sez_core#contribute'
  get  '/contact'     => 'contacts#new',         :as => 'contact'
  post '/contact'     => 'contacts#create',      :as => 'contact_create'
  get  '/game/:id'    => 'sez_core#game',        :as => 'game'
  get  '/feed'        => 'articles#feed',        :as => :feed,    :defaults => { :format => 'rss' }

  resources :articles
  resources :topics
  resources :quizzes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :body, :email, :name, :subject

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
  validates :body,  :length => { :maximum => 500 }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  before_action :check_for_mobile

  def new
    @message = Contact.new
  end

  def create
    @message = Contact.new params[:contact]

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Thank you very much!")
    else
      render :action => 'new'
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :check_for_mobile

  def new
    @message = Contact.new
  end

  def create
    @message = Contact.new params[:contact]

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Thank you very much!")
    else
      render :action => 'new'
    end
  end

end

app/views/contacts/new.html.haml
%h2 お問合せ

%p.header-lead 質問、批評、記事のアイディア、ご意見などご自由にお送りください！


- flash.each do |name, msg|
  = content_tag :div, msg, :id => "flash_#{name}", :class => "contact_flash"

= form_for @message, :url => contact_create_path do |f|
  = f.error_messages
  %fieldset
    %dl
      %dt #{f.label :name, "ご氏名"}：
      %dd #{f.text_field :name}

      %dt #{f.label :email, "メールアドレス"}
      %dd #{f.email_field :email}

      %dt #{f.label :subject, "件名"}
      %dd #{f.text_field :subject}

      %dt #{f.label :body, "コメント"}
      %dd #{f.text_area :body}

  = f.submit "送信", :class => "submit"