config/routes.rb
SEZWebsite::Application.routes.draw do

  root :to => 'sez_core#index'

  get  '/about'       => 'sez_core#about'
  get  '/archive'     => 'sez_core#archive'
  get  '/contribute'  => 'sez_core#contribute'
  get  '/contact'     => 'contacts#new',         :as => 'contact'
  post '/contact'     => 'contacts#create',      :as => 'contact_create'
  get  '/game/:id'    => 'sez_core#game',        :as => 'game'
  get  '/feed'        => 'articles#feed',        :as => :feed,    :defaults => { :format => 'rss' }

  resources :articles
  resources :topics
  resources :quizzes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/article.rb
class Article < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, :use => [:slugged, :history]

  mount_uploader :image, ImageUploader

  belongs_to :topic
  belongs_to :author
  has_many   :vocabulary_words
  has_many   :culture_notes
  has_many   :study_notes
  has_many   :tags
  has_many   :quizzes

  validates :author, :body, :description, :title, :pubdate, :pubtype, :presence => true
  validates :pubtype,
            :inclusion => {
                            :in => ['feature', 'blog', 'recipe'],
                            :message => "%{value} is not a valid publication type. Please use 'article', 'recipe' or 'blog'."
                          }
  validates :flag_message,
            :inclusion => {
                            :in => ['easy to read', 'short read', 'challenge', 'learn slang'],
                            :message => "%{value} is not a valid flag message.",
                            :allow_blank => true
                          }

  accepts_nested_attributes_for :tags,
                                :allow_destroy => true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

end

app/models/author.rb
class Author < ActiveRecord::Base

  mount_uploader :image, AuthorImageUploader

  validates :name, :presence => true

  has_many :articles

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :body, :email, :name, :subject

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
  validates :body,  :length => { :maximum => 500 }

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/culture_note.rb
class CultureNote < ActiveRecord::Base

  belongs_to :article

end

app/models/flashcard_vocab.rb
class FlashcardVocab < ActiveRecord::Base

  belongs_to :quiz

  validates :word, :translation, :vocab_type, :quiz_id, :example_sentence, :presence => true

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base

  belongs_to :article
  belongs_to :topic
  has_many   :flashcard_vocabs

  validates :name, :quiz_type, :presence => true
  validates :quiz_type, :inclusion => {
                                        :in => ['fill in the blank', 'flashcard'],
                                        :message => "%{value} is not a valid quiz type."
                                      }

end

app/models/study_note.rb
class StudyNote < ActiveRecord::Base

  belongs_to :article

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :article

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name

  has_many :articles
  has_many :quizzes

end

app/models/vocabulary_word.rb
class VocabularyWord < ActiveRecord::Base

  belongs_to :article

end

app/controllers/article_controller.rb
class ArticleController < ApplicationController

  before_action :check_for_mobile

  def show
    @article = ArticleDecorator.new Article.find(params[:id]), view_context

    gon.vocab         = @article.vocab          if @article.vocab
    gon.culture_notes = @article.culture_notes  if @article.culture_notes
    gon.study_notes   = @article.study_notes    if @article.study_notes

    #Social Media Meta
    @meta_title       = @article.title
    @meta_url         = "http://" + request.host_with_port + request.fullpath
    @meta_image       = "http://" + request.host_with_port + @article.image_url(:main)
    @meta_description = @article.description

  end

  def feed
    @articles = Article.order("pubdate DESC").limit(20)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :check_for_mobile

  def show
    @article = ArticleDecorator.new Article.find(params[:id]), view_context

    gon.vocab         = @article.vocab          if @article.vocab
    gon.culture_notes = @article.culture_notes  if @article.culture_notes
    gon.study_notes   = @article.study_notes    if @article.study_notes

    #Social Media Meta
    @meta_title       = @article.title
    @meta_url         = "http://" + request.host_with_port + request.fullpath
    @meta_image       = "http://" + request.host_with_port + @article.image_url(:main)
    @meta_description = @article.description

  end

  def feed
    @articles = Article.order("pubdate DESC").limit(20)

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  before_action :check_for_mobile

  def new
    @message = Contact.new
  end

  def create
    @message = Contact.new params[:contact]

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Thank you very much!")
    else
      render :action => 'new'
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :check_for_mobile

  def new
    @message = Contact.new
  end

  def create
    @message = Contact.new params[:contact]

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Thank you very much!")
    else
      render :action => 'new'
    end
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  def show
    @quiz = QuizDecorator.new Quiz.find(params[:id])

    gon.target_vocab = @quiz.target_vocab
    gon.option_vocab = @quiz.option_vocab
  end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  def show
    @topic = Topic.find(params[:id])
    @title = @topic.name
    @articles = Article.where(:topic_id => @topic.id).order("pubdate DESC").limit(20)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
    @topic = Topic.find(params[:id])
    @title = @topic.name
    @articles = Article.where(:topic_id => @topic.id).order("pubdate DESC").limit(20)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "SEZ"
    @title.nil? ? base_title : "#{base_title} | #{@title}"
  end

  def local_stylesheet
    "#{local_stylesheet}" if @local_stylesheet
  end

end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_message") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/views/layouts/_article_study_sections.html.haml
- unless @article.vocab.blank?
  %section#vocab
    %h3 Vocabulary
    %ul
      - @article.vocab.each do | vocab |
        = content_tag :li, :id => vocab.word.tr(" ", "_")+'_detail' do
          <strong>#{vocab.word}</strong> (#{vocab.part_of_speech}): #{vocab.definition} 【#{vocab.translation}】

- unless @article.culture_notes.blank?
  %section#culture_notes
    %h3 Culture Notes
    %ul
      - @article.culture_notes.each do | entry |
        = content_tag :li, :id => entry.title.tr(" ", "_")+'_detail' do
          <strong>#{entry.title}</strong>: #{raw entry.body}

- unless @article.study_notes.blank?
  %section#study_notes
    %h3 Study Notes
    %ul
      - @article.study_notes.each do | entry |
        = content_tag :li, :id => entry.title.tr(" ", "_")+'_detail' do
          <strong>#{entry.title}</strong>: #{raw entry.body}

- unless @article.audio.blank?
  %section#audio
    %h3 Audio
    = raw @article.audio

app/views/layouts/_article_tags.html.haml
.tags
  %h4 Tags:
  %p #{@article.tags.map { |t| t.name }.join(", ")}

app/views/layouts/_article_top_nav.html.haml
%nav#article_top_nav
  %h1 #{link_to "SEZ", root_path}
  = link_to "?", "#help_modal", :id => "help"
  #help_modal.modal_dialog
    #inner_modal
      = link_to "X", "#close", :title => "Close", :class => "close"
      %h2 SEZの使い方

      %p SEZは英語のリーディングを練習したい日本人向けのウェブサイトです。このサイトを利用して新しく興味深いものについて学んだり、リーディング力を磨いたり、英語の語彙を増やすことが出来ます。音声付きの記事もあるので、リスニングも上達することが出来ます。

      %p 記事はすべてシンプルな英語で書かれているので、中級レベルの学習者は無理なく読めるはずです

      %p 赤点線が引かれている単語にマウスポインターを合わせると、説明文が画面左下に表示されます。

      %p.example_popup
        = link_to "このリンクにマウスポインターを合わせてみて！", "", :id => "help_bubble", :class => "article_bubble_trigger"

app/views/layouts/_footer.html.haml
%footer#main-footer
  %nav
    %ul#topics
      - @topics_menu.each do |topic|
        %li #{link_to topic.name, topic}

    %ul#about
      %li #{link_to "ホーム", root_path}
      %li #{link_to "SEZとは", about_path}
      %li #{link_to "Contribute", contribute_path}
      %li #{link_to "お問合せ", contact_path}

    %ul#social-media
      %li
        = link_to image_tag('/images/fb.png', :alt => "Follow us on Facebook"), "http://www.facebook.com/SimpleEnglishZine", :title => "Follow us on Facebook"
      %li
        = link_to image_tag('/images/twitter.png', :alt => "Follow us on Twitter"), "https://twitter.com/SimpleEngZine", :title => "Follow us on Twitter"
      %li
        = link_to image_tag('/images/atom_feed.png', :alt => "Subscribe to our Atom feed"), feed_path, :title => "Subscribe to our Atom feed"

    %ul#license
      %li
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a>
      %li
        This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>

app/views/layouts/_head.html.haml
<meta charset="utf-8">

%title #{title.html_safe}

= content_for :head

= include_gon

- if mobile_device?
  = stylesheet_link_tag    "application_mobile"
  = javascript_include_tag "application_mobile"
- else
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"

= javascript_include_tag :modernizr
= csrf_meta_tags
= auto_discovery_link_tag :atom, "/feed"
= auto_discovery_link_tag :rss, "/feed.rss"

<!-- Google Analytics script -->
<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-41460687-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>

app/views/layouts/_header.html.haml
%header#main-header
  %h1
    = link_to "SEZ", root_path

  = render 'layouts/navigation_top'

app/views/layouts/_navigation_top.html.haml
%nav
  %ul
    %li
      = link_to "SEZとは", about_path
    %li
      = link_to "Contribute", contribute_path

app/views/layouts/_social_media_meta.html.haml
<!-- Facebook -->
<meta property="og:title" content="#{@meta_title ? @meta_title.html_safe : 'Simple English Zine'}"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="#{@meta_url ? @meta_url : 'http://simpleenglishzine.com'}"/>
<meta property="og:image" content="#{@meta_image ? @meta_image : 'http://simpleenglishzine.com/images/SEZ_social_media.png'}"/>
<meta property="og:site_name" content="SEZ"/>
<meta property="fb:admins" content="7204721"/>
<meta property="og:description" content="#{@meta_description ? @meta_description.html_safe : '今注目の話題から普段目にしないようなおもしろトピック満載！単語の意味も辞書要らずのポップアップで簡単チェック。ボキャブラリーがどんどん増えます！'}"/>

<!-- Twitter -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@SimpleEngZine">
<meta name="twitter:site:id" content="858363415">
<meta name="twitter:url" content="#{@meta_url ? @meta_url : 'http://simpleenglishzine.com'}">
<meta name="twitter:title" content="#{@meta_title ? @meta_title.html_safe : 'Simple English Zine'}">
<meta name="twitter:description" content="#{@meta_description ? @meta_description.html_safe : '今注目の話題から普段目にしないようなおもしろトピック満載！単語の意味も辞書要らずのポップアップで簡単チェック。ボキャブラリーがどんどん増えます！'}">
<meta name="twitter:image" content="#{@meta_image ? @meta_image : 'http://simpleenglishzine.com/images/SEZ_social_media.png'}">

app/views/layouts/_social_media_recommend.html.haml
<!-- AddThis Button BEGIN -->
.social-media-recommend
  .addthis_toolbox.addthis_default_style.addthis_32x32_style
    %a.addthis_button_facebook
    %a.addthis_button_twitter
    %a.addthis_button_digg
    %a.addthis_button_pinterest_share
    %a.addthis_button_google_plusone_share
    %a.addthis_button_stumbleupon
    %a.addthis_button_mixi
    %a.addthis_button_email
    %a.addthis_button_print
    %a.addthis_button_compact
    %a.addthis_counter.addthis_bubble_style

  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=undefined"></script>

<!-- AddThis Button END -->

app/views/layouts/_study_tools.html.haml
%ul.study-tools
  = content_tag(:li, "音声付き", :class => "includes-tool") unless article.audio.blank?
  = content_tag(:li, "文化説明", :class => "includes-tool") unless article.culture_notes.blank?
  = content_tag(:li, "単語付き", :class => "includes-tool") unless article.vocabulary_words.blank?
  = content_tag(:li, "クイズゲーム", :class => "includes-tool") unless article.quizzes.blank?
  = content_tag(:li, "学習ツールは準備中", :class => "includes-tool") if article.audio.blank? && article.culture_notes.blank? && article.vocabulary_words.blank?

app/views/layouts/application.html.haml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">

%head
  = render 'layouts/head'
  = render 'layouts/social_media_meta'

%body

  #container

    = render 'layouts/header'

    = yield

    = render 'layouts/footer'

</html>

app/views/layouts/article.html.haml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">

%head
  = render 'layouts/head'
  = render 'layouts/social_media_meta'

%body

  = render 'article/top_nav' unless mobile_device?
  = render 'article/header'  unless mobile_device?

  #wrapper

    %article

      = yield

      = render 'layouts/footer'

</html>

app/views/layouts/articles.html.haml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">

%head
  = render 'layouts/head'
  = render 'layouts/social_media_meta'

%body

  = render 'articles/top_nav' unless mobile_device?
  = render 'articles/header'  unless mobile_device?

  #wrapper

    %article

      = yield

      = render 'layouts/footer'

</html>

app/views/layouts/quizzes.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<%= render 'layouts/head' %>
<%= render 'layouts/social_media_meta' %>
</head>
<body>



<%= yield %>


</div>

</body>
</html>